### ISSUE TITLE
[Enhancement] NSP version

### ISSUE THREAD

**Issue by SMNFXCN** [McKay42/McOsu-NX#1]

**Comment by SMNFXCN** [comment]
Nevermind, I went and made a forwarder, you can add this to the readme if you would like.
Please be aware that installing this can lead to a ban.
App Name: McOsu NX
Title ID: 0537DEE981DC0000
Author: McKay
Version: 1.0.0
Make sure the McEngine.nro is in /switch/McOsu/
The NSP is completely legal. I am not responsible for any bricks or bans.
If it does not install via Goldleaf use Tinfoil. Recording and Screenshots are enabled.
Preview:
https://imgur.com/a/OnqGb03
Download:
[McOsuNX_0537DEE981DC0000.zip](https://github.com/McKay42/McOsu-NX/files/2793153/McOsuNX_0537DEE981DC0000.zip)

**Comment by McKay42** [comment]
Does this guarantee full RAM access? Because I have already created a forwarder, and the result was the same limited amount as if launched via applet HBL, which is why I didn't include it.

**Comment by LavaJockey** [comment]
I just tested this and yes it gives full RAM access!

**Comment by LavaJockey** [comment]
Only thing is that the exit button in the menu does not work.You would need to exit it through the home menu.

**Comment by SMNFXCN** [comment]
forgot to mention that it does have full ram and the exit button doesnt work but you already found out lmao
