### ISSUE TITLE
Unable to disable mouse input.

### ISSUE THREAD

**Issue by Chara-Reborn** [McKay42/McOsu-NX#3]
Disabling mouse input would help people playing using the Joycon's and touch screen.

Touch-Screen for cursor movement.
Joycons for input.

**Comment by McKay42** [comment]
I accidentally removed the options entry for this, but until I upload a new build you can just add this to your cfg:


Open `/switch/McOsu/cfg/osu.cfg` with a text editor and add this line:


`osu_disable_mousebuttons 1`

**Comment by McKay42** [comment]
I've updated the current release, since it is only such a small change.

You can redownload and replace the nro to get the options entry, or use the cfg method.
